# Create subfolder within the current working directory
dir.create("R")
dir.create("Data")
dir.create("Output")
dir.create("Output/Data")
dir.create("Output/Data/csv")
dir.create("Output/Data/excel")
dir.create("Output/Plots")
dir.create("Output/Plots/Profiles")
dir.create("Output/Plots/SamplingRates")
